### ISSUE TITLE
Instructor Feedback - Problem statement, scope, tech, planning

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [zcmarcus/Slack2Slack#2]
@zcmarcus @kpalese @sschmitt2 Looks like you three are off to a good start here!  

- [x] Can you share your proposed resources/operations in the readme? This does not have to be final; might include mvp and stretch goals.  Example POST workspaces/{source-workspace}/{target-workspace}. What formats (html, xml, plain, json) will you support in any GET requests?
- [x] Update time log/journal and add detail for the remaining two weeks to the project plan
- [x] Update list of technologies: jaxrs, Jackson, jersey, Slack api, etc.

**Comment by zcmarcus** [comment]
Item #1 implemented in README.md

**Comment by zcmarcus** [comment]
Item #3 implemented in README.md
